spring:
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST:192.168.10.14}:${MARIADB_PORT:20191}/dcim
    username: ${DB_USER:dcim}
    password: ${DB_PASS:dcim123}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties.hibernate:
      format_sql: true
      use_sql_comment: true
      jdbc.time_zone: UTC
    open-in-view: false

management:
  influx:
    metrics:
      export:
        enabled: false

influx:
  enabled: ${INFLUX_ENABLED:true}
  url: ${INFLUX_URL:http://192.168.10.14:20192}
  token: ${INFLUX_TOKEN:bJe_OHMl74F53g_O5CQsKwrEt_TQrNfmOzMLpGj724n0HbDXlqOhoz3x6_KJXARvOw0yHGdywzLde5gf4hgx_g==}
  org: ${INFLUX_ORG:vivans}
  bucket: ${INFLUX_BUCKET:dcim}
  measurement: ${INFLUX_MEASUREMENT:dcim_sensor}
